kind: ConfigMap
apiVersion: v1
metadata:
  name: rabbitmq-conf
  namespace: smartinventory
data:
  rabbitmq.conf: |
    management.load_definitions = /secret/definition.json
    default_user = guest
    default_pass = guest
    default_user_tags.administrator = true
    
    management.tcp.ip = 0.0.0.0
    management.tcp.port = 15672
    
    mqtt.listeners.tcp.default = 1883
    mqtt.default_user = mqtt-ataque
    mqtt.default_pass = ataque
    mqtt.allow_anonymous = false
    mqtt.vhost            = /mqtt
    mqtt.exchange         = amq.topic
    # 24 hours by default
    mqtt.subscription_ttl = 86400000
    mqtt.prefetch         = 10

