version: "3.9"  # optional since v1.27.0
services:
  grafana:
    image: grafana/grafana-oss:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - /data/grafana:/var/lib/grafana:rw
    networks:
      - analytics

  influxdb:
    image: influxdb:1.8-alpine
    volumes:
      - /data/influxdb:/var/lib/influxdb:rw
      - /data/config/influxdb:/etc/influxdb
    ports:
      - "8086:8086"
    networks:
      - analytics
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=
      - DOCKER_INFLUXDB_INIT_BUCKET=events

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - analytics
    volumes:
      - /data/config/prometheus:/etc/prometheus:rw

networks:
  analytics:
    name: smartinventory_analytics
    external: true
