kind: Secret
apiVersion: v1
metadata:
  name: influxdb-secret
  namespace: smartinventory-analytics
data:
  DOCKER_INFLUXDB_INIT_BUCKET: ""
  DOCKER_INFLUXDB_INIT_PASSWORD: ""
  DOCKER_INFLUXDB_INIT_USERNAME: ""
type: Opaque
