kind: Secret
apiVersion: v1
metadata:
  name: telegraf-secret
  namespace: smartinventory-analytics
data:
  INFLUX_USERNAME: ""
  INFLUX_PASSWORD: ""
  AMQP_USERNAME: ""
  AMQP_PASSWORD: ""

type: Opaque
