ssh_authorized_keys:
  - github:bat553
  - github:eloibrd
hostname: smartinv-master
boot_cmd:
  - mkdir -p /var/lib/nfs/sm
  - rc-update add rpc.statd
  - rc-update add nfs
write_files:
  - path: /etc/rancher/k3s/registries.yaml
    content: |-
      mirrors:
        registry.smartinv.local:
          endpoint:
            - "https://registry.smartinv.local:5000"
      configs:
        "registry.smartinv.local:5000":
          tls:
            insecure_skip_verify: true

k3os:
  data_sources:
    - cdrom
  modules:
    - kvm
    - nvme
    - nfs
  sysctl:
    net.ipv6.conf.all.disable_ipv6: 1
    net.ipv6.conf.default.disable_ipv6: 1
  dns_nameservers:
    - 1.1.1.1
  ntp_servers:
    - 0.us.pool.ntp.org
    - 1.us.pool.ntp.org
  token: jqQo1jbAMJezNV8zbQgBM6zwC6oE2yDUNpwTX2cI8uOEkCR4sMr6RQPQSIM8nwXPfF
  labels:
    region: los-andes-ml3
    project: smartinventory
  k3s_args:
    - server
    - "--cluster-init"