apiVersion: v1
kind: Service
metadata:
  name: redis-inv
  namespace: smartinventory
  labels:
    app: smartinventory
spec:
  ports:
    - port: 6379
  selector:
    app: smartinventory
    tier: redis-inv
  clusterIP: None
---
apiVersion: v1
kind: Pod
metadata:
  namespace: smartinventory
  name: redis-inv
  labels:
    app: smartinventory
    tier: redis-inv
spec:
  containers:
    - image: redis:3
      name: redis-inv
      ports:
        - containerPort: 6379
          name: redis-inv