apiVersion: v1
kind: Service
metadata:
  name: couchdb
  labels:
    app: smartinventory
spec:
  ports:
    - port: 5984
  selector:
    app: smartinventory
    tier: couchdb
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data-claim
  labels:
    app: smartinventory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
  labels:
    app: smartinventory
spec:
  selector:
    matchLabels:
      app: smartinventory
      tier: couchdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: smartinventory
        tier: couchdb
    spec:
      containers:
        - image: couchdb:3
          name: couchdb
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: couchdb-conf
                  key: COUCHDB_USER
                  optional: false
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-conf
                  key: COUCHDB_PASSWORD
                  optional: false
            - name: COUCHDB_SECRET
              valueFrom:
                secretKeyRef:
                  name: couchdb-conf
                  key: COUCHDB_SECRET
                  optional: false
          ports:
            - containerPort: 5984
              name: couchdb
          volumeMounts:
            - name: couchdb-data
              mountPath: /opt/couchdb/data
      volumes:
        - name: couchdb-data
          persistentVolumeClaim:
            claimName: couchdb-data-claim