apiVersion: v1
kind: Service
metadata:
  name: backoffice-psql
  labels:
    app: smartinventory
spec:
  ports:
    - port: 5432
  selector:
    app: smartinventory
    tier: backoffice-psql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-bo-data-claim
  labels:
    app: smartinventory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-psql
  labels:
    app: smartinventory
spec:
  selector:
    matchLabels:
      app: smartinventory
      tier: backoffice-psql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: smartinventory
        tier: backoffice-psql
    spec:
      containers:
        - image: postgres:14
          name: backoffice-psql
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-conf-bo
                  key: POSTGRES_PASSWORD
                  optional: false
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-conf-bo
                  key: POSTGRES_USER
                  optional: false
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-conf-bo
                  key: POSTGRES_DB
                  optional: false
          ports:
            - containerPort: 5432
              name: backoffice-psql
          volumeMounts:
            - name: postgres-bo-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-bo-data
          persistentVolumeClaim:
            claimName: postgres-bo-data-claim