apiVersion: v1
kind: Service
metadata:
  name: inv-backend
  labels:
    app: smartinventory
spec:
  ports:
    - port: 8000
  selector:
    app: smartinventory
    tier: inv-backend
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inv-backend
  labels:
    app: smartinventory
spec:
  selector:
    matchLabels:
      app: smartinventory
      tier: inv-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: smartinventory
        tier: inv-backend
    spec:
      containers:
        - image: smartinventory_inventory:preprod
          name: inv-backend
          ports:
            - containerPort: 8000
              name: inv-backend
          volumeMounts:
            - name: inv-config-vol
              readOnly: true
              mountPath: "/app/smartinv_back/secret/"
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp /app/smartinv_back/secret/inv_config.ini /app/smartinv_back/configuration.ini
      volumes:
        - name: inv-config-vol
          secret:
            secretName: inv-config
