# patch_nfs_details.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: 157.253.205.72
            - name: NFS_PATH
              value: /volume1/nfs-smartinv
      volumes:
        - name: nfs-client-root
          nfs:
            server: 157.253.205.72
            path: /volume1/nfs-smartinv
